### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by rndn123** [utahnlp/layer_augmentation#2]
when I unzipped conceptnet.py. I got json file. In the snli_extract.py file want .txt file for preprocessing   . can you tell me please, where will I get .text file

**Comment by t-li** [comment]
Hi, somehow I don't get notification from github. I only saw your post just now. Sorry about the late reply.

The snli_extract.py file is to take out sentences from the SNLI dataset files (e.g. snli_1.0_dev.txt). At the extraction step, it has nothing to do with the conceptnet files.
